const data = {
    bestselling: [
        { img: "./images/bestselling/bestselling-1.webp", id: "1" },
        { img: "./images/bestselling/bestselling-2.webp", id: "2" },
        { img: "./images/bestselling/bestselling-3.jpg", id: "3" },
        { img: "./images/bestselling/bestselling-4.jpg", id: "4" },
        { img: "./images/bestselling/bestselling-5.jpg", id: "5" },
        { img: "./images/bestselling/bestselling-6.jpg", id: "6" },
        { img: "./images/bestselling/bestselling-7.webp", id: "7" },
        { img: "./images/bestselling/bestselling-8.webp", id: "8" },
    ],
    animal: [
        { img: "./images/animal/animal-1.jpg", id: "1" },
        { img: "./images/animal/animal-2.jpg", id: "2" },
        { img: "./images/animal/animal-3.webp", id: "3" },
        { img: "./images/animal/animal-4.webp", id: "4" },
        { img: "./images/animal/animal-5.jpg", id: "5" },
        { img: "./images/animal/animal-6.webp", id: "6" },
        { img: "./images/animal/animal-7.jpg", id: "7" },
    ],
    maps: [
        { img: "./images/maps/maps-1.jpg", id: "1" },
        { img: "./images/maps/maps-2.jpg", id: "2" },
        { img: "./images/maps/maps-3.jpg", id: "3" },
        { img: "./images/maps/maps-4.jpg", id: "4" },
        { img: "./images/maps/maps-5.jpg", id: "5" },
        { img: "./images/maps/maps-6.jpg", id: "6" },
        { img: "./images/maps/maps-7.jpg", id: "7", },
        { img: "./images/maps/maps-8.webp", id: "8", more: true },
    ],
    exclusive: [
        { img: "./images/exclusive/exclusive-1.jpg", id: "1" },
        { img: "./images/exclusive/exclusive-2.webp", id: "2" },
        { img: "./images/exclusive/exclusive-3.webp", id: "3" },
        { img: "./images/exclusive/exclusive-4.webp", id: "4" },
        { img: "./images/exclusive/exclusive-5.jpg", id: "5" },
        { img: "./images/exclusive/exclusive-6.jpg", id: "6" },
    ],
}
export default data;